# Generated by Django 3.1.6 on 2021-04-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('profile_picture', models.TextField()),
                ('email_address', models.TextField(unique=True)),
                ('phone_number', models.TextField()),
                ('room_number', models.TextField()),
                ('subjects', models.ManyToManyField(to='teachers.Subject')),
            ],
        ),
    ]
