# Generated by Django 3.1.6 on 2021-04-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20210407_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='teachers/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='room_number',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
